name: Synchronize to GitHub from CodeCommit (AWS)

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: "develop"
    secrets:
      username:
        required: true
      password:
        required: true
      repo:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to CodeCommit
        run: |
          git config --local user.name 'Khanh Hoang'
          git config --local user.email 'khanh@tenxtenx.com'
          git remote add codecommit https://${{ secrets.username }}:${{ secrets.password }}@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/${{ secrets.repo }}
          git fetch codecommit ${{ inputs.branch }}
          git push origin refs/remotes/codecommit/${{ inputs.branch }}:$GITHUB_REF -f
