name: Synchronize with CodeCommit (AWS)

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: 'develop'
    secrets:
      username:
        required: true
      password:
        required: true
      repo:
        required: true

jobs:
  push-or-pull:
    name: Push or Pull (if failed)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to CodeCommit
        run: |
          git config --local user.name 'Khanh Hoang'
          git config --local user.email 'khanh@tenxtenx.com'
          git remote add codecommit https://${{ secrets.username }}:${{ secrets.password }}@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/${{ secrets.repo }}
          git push codecommit $GITHUB_REF_NAME:${{ inputs.branch }}

