name: Synchronize with CodeCommit (AWS)

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
        default: "develop"
    secrets:
      username:
        required: true
      password:
        required: true
      repo:
        required: true

jobs:
  push-or-pull:
    name: Push to CodeCommit or Pull (if failed)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to CodeCommit
        continue-on-error: true
        run: |
          git config --local user.name 'Khanh Hoang'
          git config --local user.email 'khanh@tenxtenx.com'
          git remote add codecommit https://${{ secrets.username }}:${{ secrets.password }}@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/${{ secrets.repo }}
          git push codecommit $GITHUB_REF_NAME:${{ inputs.branch }}
      - name: Pull from CodeCommit (if failed)
        if: ${{ failure() }}
        run: |
          git fetch codecommit ${{ inputs.branch }}
          git push origin refs/remotes/codecommit/${{ inputs.branch }}:$GITHUB_REF -f
